### ISSUE TITLE
Exception thrown when used with macros

### ISSUE THREAD

**Issue by Ehesp** [vegardit/dart-hotreloader#19]
Hello,

(Appreciate macros are experimental so likely this isn't something which can be fixed yet)

When editing a file which contains a macro class, the reloader throws an exception. Note this happens when user code references generated code, for example:

```
@Foo()
class Bar {
  String baz() {
    return foo;  // foo is a class property generated by the macro
  }
}
```

Changing something in this file cases the following:

```
[SEVERE] hotreloader: Hot-reloading code failed:
 Invalid argument(s): Trying to serialize orphaned procedure reference.
Orphaned procedure foo (Procedure:850402)
Orphaned named node foo (Procedure:850402)
Linked node foo (Procedure:850418)
#0      BinaryPrinter.visitProcedure (package:kernel/binary/ast_to_binary.dart:1346:7)
#1      Procedure.accept (package:kernel/ast.dart:3225:40)
#2      BinaryPrinter.writeProcedureNode (package:kernel/binary/ast_to_binary.dart:469:10)
#3      BinaryPrinter.writeProcedureNodeList (package:kernel/binary/ast_to_binary.dart:360:7)
#4      BinaryPrinter.visitClass (package:kernel/binary/ast_to_binary.dart:1282:5)
#5      Class.accept (package:kernel/ast.dart:1473:38)
#6      BinaryPrinter.writeClassNode (package:kernel/binary/ast_to_binary.dart:483:10)
#7      BinaryPrinter.writeClassNodeList (package:kernel/binary/ast_to_binary.dart:378:7)
#8      BinaryPrinter.visitLibrary (package:kernel/binary/ast_to_binary.dart:1118:5)
#9      Library.accept (package:kernel/ast.dart:589:38)
#10     BinaryPrinter.writeLibraryNode (package:kernel/binary/ast_to_binary.dart:462:10)
#11     BinaryPrinter.writeLibraries (package:kernel/binary/ast_to_binary.dart:797:9)
#12     BinaryPrinter.writeComponentFile.<anonymous closure> (package:kernel/binary/ast_to_binary.dart:607:7)
#13     Timeline.timeSync (dart:developer/timeline.dart:173:22)
#14     BinaryPrinter.writeComponentFile (package:kernel/binary/ast_to_binary.dart:588:14)
#15     serializeComponent (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:1031:11)
#16     _processLoadRequest (file:///Volumes/Work/s/w/ir/x/w/sdk/pkg/vm/bin/kernel_service.dart:942:41)
<asynchronous suspension>
```

Very elusive error :D 

Dart SDK version: 3.5.0-180.0.dev (dev) (Wed May 22 09:05:11 2024 -0700) on "macos_arm64"

**Comment by sebthom** [comment]
Thanks for reporting. PRs to solve this are welcome. But maybe this also needs to be addressed directly in the Dart runtime? Hotreloader uses a Dart API to do the code reloading.

**Comment by Ehesp** [comment]
Yep I assume this is at the Dart VM level to be honest. I'll see if I can raise an issue over there
